val fail : x:num[v | v > 10] -> num[v | v > 11] ;;
let fail = (fun x -> x + 1) ;; 

// this shouldn't go wrong
fail 11 ;;

// this should
fail 10
